### ISSUE TITLE
Variáveis de Ambiente

### ISSUE THREAD

**Issue by augustodevjs** [Moscarde/Junior_Zone#1]
Pode colocar um exemplo sobre as variaveis de ambiente?

**Comment by Moscarde** [comment]
Obrigado por reportar, realmente esqueci de completar esse campo no readme. Adicionei lá!

>Para utilizar funções com interação com o Telegram, configure as variaveis de ambiente: TOKEN com o token do seu bot, MAIN_GROUP_CHAT_ID com o id do grupo principal e TEST_GROUP_CHAT_ID com o id do grupo de teste.

**Comment by augustodevjs** [comment]
Show mano valeu!
